// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: dapplink/walletsign.proto

package walletsign

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WalletSignService_GetChainSignMethod_FullMethodName                = "/dapplink.WalletSignService/getChainSignMethod"
	WalletSignService_GetChainSchema_FullMethodName                    = "/dapplink.WalletSignService/getChainSchema"
	WalletSignService_CreateKeyPairsExportPublicKeyList_FullMethodName = "/dapplink.WalletSignService/createKeyPairsExportPublicKeyList"
	WalletSignService_CreateKeyPairsWithAddresses_FullMethodName       = "/dapplink.WalletSignService/createKeyPairsWithAddresses"
	WalletSignService_SignTransactionsMessage_FullMethodName           = "/dapplink.WalletSignService/signTransactionsMessage"
	WalletSignService_BuildAndSignTransactions_FullMethodName          = "/dapplink.WalletSignService/buildAndSignTransactions"
)

// WalletSignServiceClient is the client API for WalletSignService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalletSignServiceClient interface {
	GetChainSignMethod(ctx context.Context, in *ChainSignMethodRequest, opts ...grpc.CallOption) (*ChainSignMethodResponse, error)
	GetChainSchema(ctx context.Context, in *ChainSchemaRequest, opts ...grpc.CallOption) (*ChainSchemaResponse, error)
	// 批量生成公钥
	CreateKeyPairsExportPublicKeyList(ctx context.Context, in *CreateKeyPairAndExportPublicKeyRequest, opts ...grpc.CallOption) (*CreateKeyPairAndExportPublicKeyResponse, error)
	// 地址和公钥一起返回来
	CreateKeyPairsWithAddresses(ctx context.Context, in *CreateKeyPairsWithAddressesRequest, opts ...grpc.CallOption) (*CreateKeyPairsWithAddressesResponse, error)
	// --根据 32 字节的 hash 进行签名的过程--
	SignTransactionsMessage(ctx context.Context, in *SignTransactionsMessageRequest, opts ...grpc.CallOption) (*SignTransactionsMessageResponse, error)
	// -- 完整签名的流程--
	BuildAndSignTransactions(ctx context.Context, in *BuildAndSignTransactionsRequest, opts ...grpc.CallOption) (*BuildAndSignTransactionsResponse, error)
}

type walletSignServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletSignServiceClient(cc grpc.ClientConnInterface) WalletSignServiceClient {
	return &walletSignServiceClient{cc}
}

func (c *walletSignServiceClient) GetChainSignMethod(ctx context.Context, in *ChainSignMethodRequest, opts ...grpc.CallOption) (*ChainSignMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChainSignMethodResponse)
	err := c.cc.Invoke(ctx, WalletSignService_GetChainSignMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletSignServiceClient) GetChainSchema(ctx context.Context, in *ChainSchemaRequest, opts ...grpc.CallOption) (*ChainSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChainSchemaResponse)
	err := c.cc.Invoke(ctx, WalletSignService_GetChainSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletSignServiceClient) CreateKeyPairsExportPublicKeyList(ctx context.Context, in *CreateKeyPairAndExportPublicKeyRequest, opts ...grpc.CallOption) (*CreateKeyPairAndExportPublicKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKeyPairAndExportPublicKeyResponse)
	err := c.cc.Invoke(ctx, WalletSignService_CreateKeyPairsExportPublicKeyList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletSignServiceClient) CreateKeyPairsWithAddresses(ctx context.Context, in *CreateKeyPairsWithAddressesRequest, opts ...grpc.CallOption) (*CreateKeyPairsWithAddressesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKeyPairsWithAddressesResponse)
	err := c.cc.Invoke(ctx, WalletSignService_CreateKeyPairsWithAddresses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletSignServiceClient) SignTransactionsMessage(ctx context.Context, in *SignTransactionsMessageRequest, opts ...grpc.CallOption) (*SignTransactionsMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignTransactionsMessageResponse)
	err := c.cc.Invoke(ctx, WalletSignService_SignTransactionsMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletSignServiceClient) BuildAndSignTransactions(ctx context.Context, in *BuildAndSignTransactionsRequest, opts ...grpc.CallOption) (*BuildAndSignTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildAndSignTransactionsResponse)
	err := c.cc.Invoke(ctx, WalletSignService_BuildAndSignTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletSignServiceServer is the server API for WalletSignService service.
// All implementations should embed UnimplementedWalletSignServiceServer
// for forward compatibility.
type WalletSignServiceServer interface {
	GetChainSignMethod(context.Context, *ChainSignMethodRequest) (*ChainSignMethodResponse, error)
	GetChainSchema(context.Context, *ChainSchemaRequest) (*ChainSchemaResponse, error)
	// 批量生成公钥
	CreateKeyPairsExportPublicKeyList(context.Context, *CreateKeyPairAndExportPublicKeyRequest) (*CreateKeyPairAndExportPublicKeyResponse, error)
	// 地址和公钥一起返回来
	CreateKeyPairsWithAddresses(context.Context, *CreateKeyPairsWithAddressesRequest) (*CreateKeyPairsWithAddressesResponse, error)
	// --根据 32 字节的 hash 进行签名的过程--
	SignTransactionsMessage(context.Context, *SignTransactionsMessageRequest) (*SignTransactionsMessageResponse, error)
	// -- 完整签名的流程--
	BuildAndSignTransactions(context.Context, *BuildAndSignTransactionsRequest) (*BuildAndSignTransactionsResponse, error)
}

// UnimplementedWalletSignServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalletSignServiceServer struct{}

func (UnimplementedWalletSignServiceServer) GetChainSignMethod(context.Context, *ChainSignMethodRequest) (*ChainSignMethodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChainSignMethod not implemented")
}
func (UnimplementedWalletSignServiceServer) GetChainSchema(context.Context, *ChainSchemaRequest) (*ChainSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChainSchema not implemented")
}
func (UnimplementedWalletSignServiceServer) CreateKeyPairsExportPublicKeyList(context.Context, *CreateKeyPairAndExportPublicKeyRequest) (*CreateKeyPairAndExportPublicKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateKeyPairsExportPublicKeyList not implemented")
}
func (UnimplementedWalletSignServiceServer) CreateKeyPairsWithAddresses(context.Context, *CreateKeyPairsWithAddressesRequest) (*CreateKeyPairsWithAddressesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateKeyPairsWithAddresses not implemented")
}
func (UnimplementedWalletSignServiceServer) SignTransactionsMessage(context.Context, *SignTransactionsMessageRequest) (*SignTransactionsMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignTransactionsMessage not implemented")
}
func (UnimplementedWalletSignServiceServer) BuildAndSignTransactions(context.Context, *BuildAndSignTransactionsRequest) (*BuildAndSignTransactionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildAndSignTransactions not implemented")
}
func (UnimplementedWalletSignServiceServer) testEmbeddedByValue() {}

// UnsafeWalletSignServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletSignServiceServer will
// result in compilation errors.
type UnsafeWalletSignServiceServer interface {
	mustEmbedUnimplementedWalletSignServiceServer()
}

func RegisterWalletSignServiceServer(s grpc.ServiceRegistrar, srv WalletSignServiceServer) {
	// If the following call panics, it indicates UnimplementedWalletSignServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalletSignService_ServiceDesc, srv)
}

func _WalletSignService_GetChainSignMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainSignMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSignServiceServer).GetChainSignMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletSignService_GetChainSignMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSignServiceServer).GetChainSignMethod(ctx, req.(*ChainSignMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletSignService_GetChainSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSignServiceServer).GetChainSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletSignService_GetChainSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSignServiceServer).GetChainSchema(ctx, req.(*ChainSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletSignService_CreateKeyPairsExportPublicKeyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKeyPairAndExportPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSignServiceServer).CreateKeyPairsExportPublicKeyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletSignService_CreateKeyPairsExportPublicKeyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSignServiceServer).CreateKeyPairsExportPublicKeyList(ctx, req.(*CreateKeyPairAndExportPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletSignService_CreateKeyPairsWithAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKeyPairsWithAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSignServiceServer).CreateKeyPairsWithAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletSignService_CreateKeyPairsWithAddresses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSignServiceServer).CreateKeyPairsWithAddresses(ctx, req.(*CreateKeyPairsWithAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletSignService_SignTransactionsMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignTransactionsMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSignServiceServer).SignTransactionsMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletSignService_SignTransactionsMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSignServiceServer).SignTransactionsMessage(ctx, req.(*SignTransactionsMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletSignService_BuildAndSignTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildAndSignTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSignServiceServer).BuildAndSignTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletSignService_BuildAndSignTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSignServiceServer).BuildAndSignTransactions(ctx, req.(*BuildAndSignTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletSignService_ServiceDesc is the grpc.ServiceDesc for WalletSignService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletSignService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dapplink.WalletSignService",
	HandlerType: (*WalletSignServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getChainSignMethod",
			Handler:    _WalletSignService_GetChainSignMethod_Handler,
		},
		{
			MethodName: "getChainSchema",
			Handler:    _WalletSignService_GetChainSchema_Handler,
		},
		{
			MethodName: "createKeyPairsExportPublicKeyList",
			Handler:    _WalletSignService_CreateKeyPairsExportPublicKeyList_Handler,
		},
		{
			MethodName: "createKeyPairsWithAddresses",
			Handler:    _WalletSignService_CreateKeyPairsWithAddresses_Handler,
		},
		{
			MethodName: "signTransactionsMessage",
			Handler:    _WalletSignService_SignTransactionsMessage_Handler,
		},
		{
			MethodName: "buildAndSignTransactions",
			Handler:    _WalletSignService_BuildAndSignTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dapplink/walletsign.proto",
}
