// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: dapplink/walletsign.proto

package walletsign

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WalletSignService_GetChainSignMethod_FullMethodName                = "/dapplink.WalletSignService/getChainSignMethod"
	WalletSignService_GetChainSchema_FullMethodName                    = "/dapplink.WalletSignService/getChainSchema"
	WalletSignService_CreateKeyPairsExportPublicKeyList_FullMethodName = "/dapplink.WalletSignService/createKeyPairsExportPublicKeyList"
	WalletSignService_CreateKeyPairsWithAddresses_FullMethodName       = "/dapplink.WalletSignService/createKeyPairsWithAddresses"
	WalletSignService_SignTransactionsMessage_FullMethodName           = "/dapplink.WalletSignService/signTransactionsMessage"
	WalletSignService_BuildAndSignTransactions_FullMethodName          = "/dapplink.WalletSignService/buildAndSignTransactions"
	WalletSignService_Sign7702Authorization_FullMethodName             = "/dapplink.WalletSignService/sign7702Authorization"
	WalletSignService_SignUserOperation_FullMethodName                 = "/dapplink.WalletSignService/signUserOperation"
)

// WalletSignServiceClient is the client API for WalletSignService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalletSignServiceClient interface {
	GetChainSignMethod(ctx context.Context, in *ChainSignMethodRequest, opts ...grpc.CallOption) (*ChainSignMethodResponse, error)
	GetChainSchema(ctx context.Context, in *ChainSchemaRequest, opts ...grpc.CallOption) (*ChainSchemaResponse, error)
	// 批量生成公钥
	CreateKeyPairsExportPublicKeyList(ctx context.Context, in *CreateKeyPairAndExportPublicKeyRequest, opts ...grpc.CallOption) (*CreateKeyPairAndExportPublicKeyResponse, error)
	// 地址和公钥一起返回来
	CreateKeyPairsWithAddresses(ctx context.Context, in *CreateKeyPairsWithAddressesRequest, opts ...grpc.CallOption) (*CreateKeyPairsWithAddressesResponse, error)
	// --根据 32 字节的 hash 进行签名的过程--
	SignTransactionsMessage(ctx context.Context, in *SignTransactionsMessageRequest, opts ...grpc.CallOption) (*SignTransactionsMessageResponse, error)
	// -- 完整签名的流程--
	BuildAndSignTransactions(ctx context.Context, in *BuildAndSignTransactionsRequest, opts ...grpc.CallOption) (*BuildAndSignTransactionsResponse, error)
	// EIP-7702 + ERC-4337
	Sign7702Authorization(ctx context.Context, in *Sign7702AuthRequest, opts ...grpc.CallOption) (*Sign7702AuthResponse, error)
	SignUserOperation(ctx context.Context, in *SignUserOpRequest, opts ...grpc.CallOption) (*SignUserOpResponse, error)
}

type walletSignServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletSignServiceClient(cc grpc.ClientConnInterface) WalletSignServiceClient {
	return &walletSignServiceClient{cc}
}

func (c *walletSignServiceClient) GetChainSignMethod(ctx context.Context, in *ChainSignMethodRequest, opts ...grpc.CallOption) (*ChainSignMethodResponse, error) {
	out := new(ChainSignMethodResponse)
	err := c.cc.Invoke(ctx, WalletSignService_GetChainSignMethod_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletSignServiceClient) GetChainSchema(ctx context.Context, in *ChainSchemaRequest, opts ...grpc.CallOption) (*ChainSchemaResponse, error) {
	out := new(ChainSchemaResponse)
	err := c.cc.Invoke(ctx, WalletSignService_GetChainSchema_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletSignServiceClient) CreateKeyPairsExportPublicKeyList(ctx context.Context, in *CreateKeyPairAndExportPublicKeyRequest, opts ...grpc.CallOption) (*CreateKeyPairAndExportPublicKeyResponse, error) {
	out := new(CreateKeyPairAndExportPublicKeyResponse)
	err := c.cc.Invoke(ctx, WalletSignService_CreateKeyPairsExportPublicKeyList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletSignServiceClient) CreateKeyPairsWithAddresses(ctx context.Context, in *CreateKeyPairsWithAddressesRequest, opts ...grpc.CallOption) (*CreateKeyPairsWithAddressesResponse, error) {
	out := new(CreateKeyPairsWithAddressesResponse)
	err := c.cc.Invoke(ctx, WalletSignService_CreateKeyPairsWithAddresses_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletSignServiceClient) SignTransactionsMessage(ctx context.Context, in *SignTransactionsMessageRequest, opts ...grpc.CallOption) (*SignTransactionsMessageResponse, error) {
	out := new(SignTransactionsMessageResponse)
	err := c.cc.Invoke(ctx, WalletSignService_SignTransactionsMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletSignServiceClient) BuildAndSignTransactions(ctx context.Context, in *BuildAndSignTransactionsRequest, opts ...grpc.CallOption) (*BuildAndSignTransactionsResponse, error) {
	out := new(BuildAndSignTransactionsResponse)
	err := c.cc.Invoke(ctx, WalletSignService_BuildAndSignTransactions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletSignServiceClient) Sign7702Authorization(ctx context.Context, in *Sign7702AuthRequest, opts ...grpc.CallOption) (*Sign7702AuthResponse, error) {
	out := new(Sign7702AuthResponse)
	err := c.cc.Invoke(ctx, WalletSignService_Sign7702Authorization_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletSignServiceClient) SignUserOperation(ctx context.Context, in *SignUserOpRequest, opts ...grpc.CallOption) (*SignUserOpResponse, error) {
	out := new(SignUserOpResponse)
	err := c.cc.Invoke(ctx, WalletSignService_SignUserOperation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletSignServiceServer is the server API for WalletSignService service.
// All implementations should embed UnimplementedWalletSignServiceServer
// for forward compatibility
type WalletSignServiceServer interface {
	GetChainSignMethod(context.Context, *ChainSignMethodRequest) (*ChainSignMethodResponse, error)
	GetChainSchema(context.Context, *ChainSchemaRequest) (*ChainSchemaResponse, error)
	// 批量生成公钥
	CreateKeyPairsExportPublicKeyList(context.Context, *CreateKeyPairAndExportPublicKeyRequest) (*CreateKeyPairAndExportPublicKeyResponse, error)
	// 地址和公钥一起返回来
	CreateKeyPairsWithAddresses(context.Context, *CreateKeyPairsWithAddressesRequest) (*CreateKeyPairsWithAddressesResponse, error)
	// --根据 32 字节的 hash 进行签名的过程--
	SignTransactionsMessage(context.Context, *SignTransactionsMessageRequest) (*SignTransactionsMessageResponse, error)
	// -- 完整签名的流程--
	BuildAndSignTransactions(context.Context, *BuildAndSignTransactionsRequest) (*BuildAndSignTransactionsResponse, error)
	// EIP-7702 + ERC-4337
	Sign7702Authorization(context.Context, *Sign7702AuthRequest) (*Sign7702AuthResponse, error)
	SignUserOperation(context.Context, *SignUserOpRequest) (*SignUserOpResponse, error)
}

// UnimplementedWalletSignServiceServer should be embedded to have forward compatible implementations.
type UnimplementedWalletSignServiceServer struct {
}

func (UnimplementedWalletSignServiceServer) GetChainSignMethod(context.Context, *ChainSignMethodRequest) (*ChainSignMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChainSignMethod not implemented")
}
func (UnimplementedWalletSignServiceServer) GetChainSchema(context.Context, *ChainSchemaRequest) (*ChainSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChainSchema not implemented")
}
func (UnimplementedWalletSignServiceServer) CreateKeyPairsExportPublicKeyList(context.Context, *CreateKeyPairAndExportPublicKeyRequest) (*CreateKeyPairAndExportPublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKeyPairsExportPublicKeyList not implemented")
}
func (UnimplementedWalletSignServiceServer) CreateKeyPairsWithAddresses(context.Context, *CreateKeyPairsWithAddressesRequest) (*CreateKeyPairsWithAddressesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKeyPairsWithAddresses not implemented")
}
func (UnimplementedWalletSignServiceServer) SignTransactionsMessage(context.Context, *SignTransactionsMessageRequest) (*SignTransactionsMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignTransactionsMessage not implemented")
}
func (UnimplementedWalletSignServiceServer) BuildAndSignTransactions(context.Context, *BuildAndSignTransactionsRequest) (*BuildAndSignTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuildAndSignTransactions not implemented")
}
func (UnimplementedWalletSignServiceServer) Sign7702Authorization(context.Context, *Sign7702AuthRequest) (*Sign7702AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sign7702Authorization not implemented")
}
func (UnimplementedWalletSignServiceServer) SignUserOperation(context.Context, *SignUserOpRequest) (*SignUserOpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUserOperation not implemented")
}

// UnsafeWalletSignServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletSignServiceServer will
// result in compilation errors.
type UnsafeWalletSignServiceServer interface {
	mustEmbedUnimplementedWalletSignServiceServer()
}

func RegisterWalletSignServiceServer(s grpc.ServiceRegistrar, srv WalletSignServiceServer) {
	s.RegisterService(&WalletSignService_ServiceDesc, srv)
}

func _WalletSignService_GetChainSignMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainSignMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSignServiceServer).GetChainSignMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletSignService_GetChainSignMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSignServiceServer).GetChainSignMethod(ctx, req.(*ChainSignMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletSignService_GetChainSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSignServiceServer).GetChainSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletSignService_GetChainSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSignServiceServer).GetChainSchema(ctx, req.(*ChainSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletSignService_CreateKeyPairsExportPublicKeyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKeyPairAndExportPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSignServiceServer).CreateKeyPairsExportPublicKeyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletSignService_CreateKeyPairsExportPublicKeyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSignServiceServer).CreateKeyPairsExportPublicKeyList(ctx, req.(*CreateKeyPairAndExportPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletSignService_CreateKeyPairsWithAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKeyPairsWithAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSignServiceServer).CreateKeyPairsWithAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletSignService_CreateKeyPairsWithAddresses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSignServiceServer).CreateKeyPairsWithAddresses(ctx, req.(*CreateKeyPairsWithAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletSignService_SignTransactionsMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignTransactionsMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSignServiceServer).SignTransactionsMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletSignService_SignTransactionsMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSignServiceServer).SignTransactionsMessage(ctx, req.(*SignTransactionsMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletSignService_BuildAndSignTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildAndSignTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSignServiceServer).BuildAndSignTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletSignService_BuildAndSignTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSignServiceServer).BuildAndSignTransactions(ctx, req.(*BuildAndSignTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletSignService_Sign7702Authorization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Sign7702AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSignServiceServer).Sign7702Authorization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletSignService_Sign7702Authorization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSignServiceServer).Sign7702Authorization(ctx, req.(*Sign7702AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletSignService_SignUserOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUserOpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletSignServiceServer).SignUserOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletSignService_SignUserOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletSignServiceServer).SignUserOperation(ctx, req.(*SignUserOpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletSignService_ServiceDesc is the grpc.ServiceDesc for WalletSignService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletSignService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dapplink.WalletSignService",
	HandlerType: (*WalletSignServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getChainSignMethod",
			Handler:    _WalletSignService_GetChainSignMethod_Handler,
		},
		{
			MethodName: "getChainSchema",
			Handler:    _WalletSignService_GetChainSchema_Handler,
		},
		{
			MethodName: "createKeyPairsExportPublicKeyList",
			Handler:    _WalletSignService_CreateKeyPairsExportPublicKeyList_Handler,
		},
		{
			MethodName: "createKeyPairsWithAddresses",
			Handler:    _WalletSignService_CreateKeyPairsWithAddresses_Handler,
		},
		{
			MethodName: "signTransactionsMessage",
			Handler:    _WalletSignService_SignTransactionsMessage_Handler,
		},
		{
			MethodName: "buildAndSignTransactions",
			Handler:    _WalletSignService_BuildAndSignTransactions_Handler,
		},
		{
			MethodName: "sign7702Authorization",
			Handler:    _WalletSignService_Sign7702Authorization_Handler,
		},
		{
			MethodName: "signUserOperation",
			Handler:    _WalletSignService_SignUserOperation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dapplink/walletsign.proto",
}
