// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: dapplink/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReturnCode int32

const (
	ReturnCode_SUCCESS ReturnCode = 0
	ReturnCode_ERROR   ReturnCode = 1
)

// Enum value maps for ReturnCode.
var (
	ReturnCode_name = map[int32]string{
		0: "SUCCESS",
		1: "ERROR",
	}
	ReturnCode_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   1,
	}
)

func (x ReturnCode) Enum() *ReturnCode {
	p := new(ReturnCode)
	*p = x
	return p
}

func (x ReturnCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReturnCode) Descriptor() protoreflect.EnumDescriptor {
	return file_dapplink_common_proto_enumTypes[0].Descriptor()
}

func (ReturnCode) Type() protoreflect.EnumType {
	return &file_dapplink_common_proto_enumTypes[0]
}

func (x ReturnCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReturnCode.Descriptor instead.
func (ReturnCode) EnumDescriptor() ([]byte, []int) {
	return file_dapplink_common_proto_rawDescGZIP(), []int{0}
}

type PublicKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	mi := &file_dapplink_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_dapplink_common_proto_rawDescGZIP(), []int{0}
}

func (x *PublicKey) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PublicKey) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

var File_dapplink_common_proto protoreflect.FileDescriptor

const file_dapplink_common_proto_rawDesc = "" +
	"\n" +
	"\x15dapplink/common.proto\x12\bdapplink\">\n" +
	"\tPublicKey\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey*$\n" +
	"\n" +
	"ReturnCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x01B\x14Z\x12../protobuf/commonb\x06proto3"

var (
	file_dapplink_common_proto_rawDescOnce sync.Once
	file_dapplink_common_proto_rawDescData []byte
)

func file_dapplink_common_proto_rawDescGZIP() []byte {
	file_dapplink_common_proto_rawDescOnce.Do(func() {
		file_dapplink_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dapplink_common_proto_rawDesc), len(file_dapplink_common_proto_rawDesc)))
	})
	return file_dapplink_common_proto_rawDescData
}

var file_dapplink_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dapplink_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dapplink_common_proto_goTypes = []any{
	(ReturnCode)(0),   // 0: dapplink.ReturnCode
	(*PublicKey)(nil), // 1: dapplink.PublicKey
}
var file_dapplink_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dapplink_common_proto_init() }
func file_dapplink_common_proto_init() {
	if File_dapplink_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dapplink_common_proto_rawDesc), len(file_dapplink_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dapplink_common_proto_goTypes,
		DependencyIndexes: file_dapplink_common_proto_depIdxs,
		EnumInfos:         file_dapplink_common_proto_enumTypes,
		MessageInfos:      file_dapplink_common_proto_msgTypes,
	}.Build()
	File_dapplink_common_proto = out.File
	file_dapplink_common_proto_goTypes = nil
	file_dapplink_common_proto_depIdxs = nil
}
