// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: dapplink/riskcontroller.proto

package riskcontroller

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RiskControllerServices_CheckAmlAddress_FullMethodName        = "/dapplink.RiskControllerServices/checkAmlAddress"
	RiskControllerServices_CheckChainTransactions_FullMethodName = "/dapplink.RiskControllerServices/checkChainTransactions"
	RiskControllerServices_SubmitWithdraw_FullMethodName         = "/dapplink.RiskControllerServices/submitWithdraw"
	RiskControllerServices_CheckOfflineWithdraw_FullMethodName   = "/dapplink.RiskControllerServices/checkOfflineWithdraw"
	RiskControllerServices_SubmitTransactionFlow_FullMethodName  = "/dapplink.RiskControllerServices/submitTransactionFlow"
	RiskControllerServices_CheckedTransactionFlow_FullMethodName = "/dapplink.RiskControllerServices/checkedTransactionFlow"
)

// RiskControllerServicesClient is the client API for RiskControllerServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RiskControllerServicesClient interface {
	CheckAmlAddress(ctx context.Context, in *CheckAmlAddressRequest, opts ...grpc.CallOption) (*CheckAmlAddressResponse, error)
	CheckChainTransactions(ctx context.Context, in *CheckChainTransactionsRequest, opts ...grpc.CallOption) (*CheckChainTransactionsResponse, error)
	SubmitWithdraw(ctx context.Context, in *RiskWithdrawTransactionRequest, opts ...grpc.CallOption) (*RiskWithdrawTransactionResponse, error)
	CheckOfflineWithdraw(ctx context.Context, in *CheckOfflineTransactionRequest, opts ...grpc.CallOption) (*CheckOfflineTransactionResponse, error)
	SubmitTransactionFlow(ctx context.Context, in *TransactionFlowRequest, opts ...grpc.CallOption) (*TransactionFlowResponse, error)
	CheckedTransactionFlow(ctx context.Context, in *TransactionFlowCheckedRequest, opts ...grpc.CallOption) (*TransactionFlowCheckedResponse, error)
}

type riskControllerServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewRiskControllerServicesClient(cc grpc.ClientConnInterface) RiskControllerServicesClient {
	return &riskControllerServicesClient{cc}
}

func (c *riskControllerServicesClient) CheckAmlAddress(ctx context.Context, in *CheckAmlAddressRequest, opts ...grpc.CallOption) (*CheckAmlAddressResponse, error) {
	out := new(CheckAmlAddressResponse)
	err := c.cc.Invoke(ctx, RiskControllerServices_CheckAmlAddress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskControllerServicesClient) CheckChainTransactions(ctx context.Context, in *CheckChainTransactionsRequest, opts ...grpc.CallOption) (*CheckChainTransactionsResponse, error) {
	out := new(CheckChainTransactionsResponse)
	err := c.cc.Invoke(ctx, RiskControllerServices_CheckChainTransactions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskControllerServicesClient) SubmitWithdraw(ctx context.Context, in *RiskWithdrawTransactionRequest, opts ...grpc.CallOption) (*RiskWithdrawTransactionResponse, error) {
	out := new(RiskWithdrawTransactionResponse)
	err := c.cc.Invoke(ctx, RiskControllerServices_SubmitWithdraw_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskControllerServicesClient) CheckOfflineWithdraw(ctx context.Context, in *CheckOfflineTransactionRequest, opts ...grpc.CallOption) (*CheckOfflineTransactionResponse, error) {
	out := new(CheckOfflineTransactionResponse)
	err := c.cc.Invoke(ctx, RiskControllerServices_CheckOfflineWithdraw_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskControllerServicesClient) SubmitTransactionFlow(ctx context.Context, in *TransactionFlowRequest, opts ...grpc.CallOption) (*TransactionFlowResponse, error) {
	out := new(TransactionFlowResponse)
	err := c.cc.Invoke(ctx, RiskControllerServices_SubmitTransactionFlow_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskControllerServicesClient) CheckedTransactionFlow(ctx context.Context, in *TransactionFlowCheckedRequest, opts ...grpc.CallOption) (*TransactionFlowCheckedResponse, error) {
	out := new(TransactionFlowCheckedResponse)
	err := c.cc.Invoke(ctx, RiskControllerServices_CheckedTransactionFlow_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiskControllerServicesServer is the server API for RiskControllerServices service.
// All implementations should embed UnimplementedRiskControllerServicesServer
// for forward compatibility
type RiskControllerServicesServer interface {
	CheckAmlAddress(context.Context, *CheckAmlAddressRequest) (*CheckAmlAddressResponse, error)
	CheckChainTransactions(context.Context, *CheckChainTransactionsRequest) (*CheckChainTransactionsResponse, error)
	SubmitWithdraw(context.Context, *RiskWithdrawTransactionRequest) (*RiskWithdrawTransactionResponse, error)
	CheckOfflineWithdraw(context.Context, *CheckOfflineTransactionRequest) (*CheckOfflineTransactionResponse, error)
	SubmitTransactionFlow(context.Context, *TransactionFlowRequest) (*TransactionFlowResponse, error)
	CheckedTransactionFlow(context.Context, *TransactionFlowCheckedRequest) (*TransactionFlowCheckedResponse, error)
}

// UnimplementedRiskControllerServicesServer should be embedded to have forward compatible implementations.
type UnimplementedRiskControllerServicesServer struct {
}

func (UnimplementedRiskControllerServicesServer) CheckAmlAddress(context.Context, *CheckAmlAddressRequest) (*CheckAmlAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAmlAddress not implemented")
}
func (UnimplementedRiskControllerServicesServer) CheckChainTransactions(context.Context, *CheckChainTransactionsRequest) (*CheckChainTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckChainTransactions not implemented")
}
func (UnimplementedRiskControllerServicesServer) SubmitWithdraw(context.Context, *RiskWithdrawTransactionRequest) (*RiskWithdrawTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitWithdraw not implemented")
}
func (UnimplementedRiskControllerServicesServer) CheckOfflineWithdraw(context.Context, *CheckOfflineTransactionRequest) (*CheckOfflineTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckOfflineWithdraw not implemented")
}
func (UnimplementedRiskControllerServicesServer) SubmitTransactionFlow(context.Context, *TransactionFlowRequest) (*TransactionFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitTransactionFlow not implemented")
}
func (UnimplementedRiskControllerServicesServer) CheckedTransactionFlow(context.Context, *TransactionFlowCheckedRequest) (*TransactionFlowCheckedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckedTransactionFlow not implemented")
}

// UnsafeRiskControllerServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiskControllerServicesServer will
// result in compilation errors.
type UnsafeRiskControllerServicesServer interface {
	mustEmbedUnimplementedRiskControllerServicesServer()
}

func RegisterRiskControllerServicesServer(s grpc.ServiceRegistrar, srv RiskControllerServicesServer) {
	s.RegisterService(&RiskControllerServices_ServiceDesc, srv)
}

func _RiskControllerServices_CheckAmlAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAmlAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskControllerServicesServer).CheckAmlAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskControllerServices_CheckAmlAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskControllerServicesServer).CheckAmlAddress(ctx, req.(*CheckAmlAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskControllerServices_CheckChainTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckChainTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskControllerServicesServer).CheckChainTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskControllerServices_CheckChainTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskControllerServicesServer).CheckChainTransactions(ctx, req.(*CheckChainTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskControllerServices_SubmitWithdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RiskWithdrawTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskControllerServicesServer).SubmitWithdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskControllerServices_SubmitWithdraw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskControllerServicesServer).SubmitWithdraw(ctx, req.(*RiskWithdrawTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskControllerServices_CheckOfflineWithdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckOfflineTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskControllerServicesServer).CheckOfflineWithdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskControllerServices_CheckOfflineWithdraw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskControllerServicesServer).CheckOfflineWithdraw(ctx, req.(*CheckOfflineTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskControllerServices_SubmitTransactionFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskControllerServicesServer).SubmitTransactionFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskControllerServices_SubmitTransactionFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskControllerServicesServer).SubmitTransactionFlow(ctx, req.(*TransactionFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskControllerServices_CheckedTransactionFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionFlowCheckedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskControllerServicesServer).CheckedTransactionFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskControllerServices_CheckedTransactionFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskControllerServicesServer).CheckedTransactionFlow(ctx, req.(*TransactionFlowCheckedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RiskControllerServices_ServiceDesc is the grpc.ServiceDesc for RiskControllerServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RiskControllerServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dapplink.RiskControllerServices",
	HandlerType: (*RiskControllerServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "checkAmlAddress",
			Handler:    _RiskControllerServices_CheckAmlAddress_Handler,
		},
		{
			MethodName: "checkChainTransactions",
			Handler:    _RiskControllerServices_CheckChainTransactions_Handler,
		},
		{
			MethodName: "submitWithdraw",
			Handler:    _RiskControllerServices_SubmitWithdraw_Handler,
		},
		{
			MethodName: "checkOfflineWithdraw",
			Handler:    _RiskControllerServices_CheckOfflineWithdraw_Handler,
		},
		{
			MethodName: "submitTransactionFlow",
			Handler:    _RiskControllerServices_SubmitTransactionFlow_Handler,
		},
		{
			MethodName: "checkedTransactionFlow",
			Handler:    _RiskControllerServices_CheckedTransactionFlow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dapplink/riskcontroller.proto",
}
